var Data=[
    {tittle:"Math",about:"Mathematics simply means to learn or to study or gain knowledge. The theories and concepts given in mathematics",src:"https://tse4.mm.bing.net/th?id=OIP.BGO60YRFL_Iwr0E-rItojwHaDG&pid=Api&P=0&h=180"},
    {tittle:"Math",about:"Mathematics simply means to learn or to study or gain knowledge. The theories and concepts given in mathematics help us ",src:"https://tse4.mm.bing.net/th?id=OIP.BGO60YRFL_Iwr0E-rItojwHaDG&pid=Api&P=0&h=180"},
    {tittle:"Math",about:"Mathematics simply means to learn or to study or gain knowledge. The theories and concepts given in mathematics help us",src:"https://tse4.mm.bing.net/th?id=OIP.BGO60YRFL_Iwr0E-rItojwHaDG&pid=Api&P=0&h=180"},
    {tittle:"Physics",about:"The most popular Physics Course After 12th are the degree courses that are the UG Level courses. Though, physics certificate courses and physics diploma courses are also availed by students as crash courses on the subject, or any particular topic",src:"https://tse2.mm.bing.net/th?id=OIP.cx9oGV6pbkSmVG8cPmHdZgAAAA&pid=Api&P=0&h=180"},
    {tittle:"Physics",about:"The most popular Physics Course After 12th are the degree courses that are the UG Level courses. Though, physics certificate courses and physics diploma courses are also availed by students as crash courses on the subject, or any particular topic",src:"https://tse2.mm.bing.net/th?id=OIP.cx9oGV6pbkSmVG8cPmHdZgAAAA&pid=Api&P=0&h=180"},
    {tittle:"Physics",about:"The most popular Physics Course After 12th are the degree courses that are the UG Level courses. Though, physics certificate courses and physics diploma courses are also availed by students as crash courses on the subject, or any particular topic",src:"https://tse2.mm.bing.net/th?id=OIP.cx9oGV6pbkSmVG8cPmHdZgAAAA&pid=Api&P=0&h=180"},
    {tittle:"Chemistry",about:"This course introduces you to Julia as a first programming language. Julia is a high-level, high-performance dynamic programming language developed specifically for scientific computing.",src:"https://tse1.mm.bing.net/th?id=OIP.EaRSwtsHkR-DqhQyiEQY4gHaFj&pid=Api&P=0&h=180"},
    {tittle:"Chemistry",about:"This course introduces you to Julia as a first programming language. Julia is a high-level, high-performance dynamic programming language developed specifically for scientific computing.",src:"https://tse1.mm.bing.net/th?id=OIP.EaRSwtsHkR-DqhQyiEQY4gHaFj&pid=Api&P=0&h=180"},
    {tittle:"Hellow",about:"hey these is avan singh",src:"https://tse3.mm.bing.net/th?id=OIP.CnJiVxrH6NgoJxqTReH6EwAAAA&pid=Api&P=0&h=180"},
    {tittle:"Hellow",about:"hey these is avan singh",src:"https://tse3.mm.bing.net/th?id=OIP.CnJiVxrH6NgoJxqTReH6EwAAAA&pid=Api&P=0&h=180"},
    {tittle:"Hellow",about:"hey these is avan singh",src:"https://tse3.mm.bing.net/th?id=OIP.CnJiVxrH6NgoJxqTReH6EwAAAA&pid=Api&P=0&h=180"},
]

export default Data;